version: '3.6'
services:
  postgres:
    image: postgres:15
    container_name: devlinks_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devlinks
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:v2.32.0
    container_name: devlinks_hasura
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      # Connect Hasura to Postgres
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/devlinks
      # Admin secret for console access
      HASURA_GRAPHQL_ADMIN_SECRET: sdv^un46z%04%DMFTX&8WvCW
      # JWT config for your Express tokens
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"supersecret123supersecret123supersecret123"}'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
    volumes:
      # Mount your SQL migrations so Hasura can track or you can run them manually
      - ./migrations:/hasura-migrations

volumes:
  pgdata:
